### ISSUE TITLE
direct eval warning when bundling with esbuild

### ISSUE THREAD

**Issue by leebenmorris** [imranbarbhuiya/esbuild-plugins-node-modules-polyfill#31]
When building code for Cypress using esbuild and this plugin I get the following warning:

Warning: G] Using direct eval with a bundler is not recommended and may cause problems [direct-eval]

    node-modules-polyfills:crypto:28833:9:
      28833 │   return eval((this || _global$b).code);
            ╵          ~~~~

  You can read more about direct eval and bundling here: https://esbuild.github.io/link/direct-eval

Should I be concerned about this?

**Comment by imranbarbhuiya** [comment]
This lib doesn't provide the source code of these modules. It depends on https://github.com/Aslemammad/modern-node-polyfills
which uses https://github.com/jspm/jspm-core I search their source code but can't find any usage of `eval`. I'll look into it.

Also if u are bundling only for testing, ig you can ignore this warning but for production bundles, this can cause issues.

Can you give me a minimal repro of this issue?

**Comment by imranbarbhuiya** [comment]
For now, I fixed in my lib and published v1.0.14, if it gets fixed in upstream, I'll revert my changes
